Repository naymspace/backpex, pull requests merged in 2024-04, with the labels that each got.

#193 Enable dynamic select options and improve docs
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/textarea.ex
  lib/backpex/fields/url.ex
Labels: feature

#195 Improve prompt option
  guides/upgrading/v0.2.md
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/many_to_many.ex
  lib/backpex/fields/multi_select.ex
  lib/backpex/fields/select.ex
Labels: breaking-change

#199 Fix dynamic select options
  lib/backpex/fields/select.ex
Labels: bug

#205 Add category select filter to post resource
  demo/lib/demo_web/filters/post_category_select.ex
  demo/lib/demo_web/live/post_live.ex
  lib/backpex/filters/select.ex
Labels: demo

#210 Remove use phoenix html
  lib/backpex_web.ex
Labels: ignore-for-release

#209 #91 add `custom_alias` to fields
  demo/lib/demo_web/live/post_live.ex
  lib/backpex/field.ex
  lib/backpex/live_resource.ex
  lib/backpex/resource.ex
Labels: feature

#212 Bump phoenix_html to 4.1 and add pheonix_html_helpers
  demo/lib/demo_web/components/core_components.ex
  demo/lib/demo_web/components/layouts/root.html.heex
  demo/mix.exs
  demo/mix.lock
  lib/backpex/fields/has_many_through.ex
  mix.exs
  mix.lock
Labels: dependencies

#215 Fix form error translation
  lib/backpex/html/form.ex
Labels: bug

#220 Improve pipeline
  .github/workflows/ci.yml
Labels: ignore-for-release

#224 Fix filter label is not displayed with atom values in filter options
  lib/backpex/filters/boolean.ex
  lib/backpex/filters/multi_select.ex
  lib/backpex/filters/select.ex
Labels: bug

#222 Fix custom alias causes nil bindings in query
  lib/backpex/resource.ex
Labels: bug

#225 Add index edit for date fields
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/live_resource.ex
Labels: feature

#226 Make filter label configurable in filter definition
  demo/lib/demo_web/live/post_live.ex
  demo/lib/demo_web/live/product_live.ex
  lib/backpex/filters/filter.ex
  lib/backpex/html/resource.ex
Labels: feature

#227 Add index edit for belongs to field
  demo/lib/demo_web/live/post_live.ex
  lib/backpex/fields/belongs_to.ex
  lib/backpex/live_resource.ex
Labels: feature

#231 Fix truncate does not cut text in some fields
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/many_to_many.ex
  lib/backpex/fields/multi_select.ex
Labels: bug

#240 Add `index_row_class` option
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/live_resource.ex
Labels: feature
