Repository naymspace/backpex, pull requests merged in 2024-07, with the labels that each got.

#436 Update installation.md
  guides/get_started/installation.md
Labels: documentation

#438 Add missing "New" in created message
  lib/backpex/live_resource.ex
Labels: bug

#431 Fix filter badge close icon
  lib/backpex/html/resource.ex
Labels: bug

#444 Move filter_badge component to CoreComponents
  lib/backpex/html/core_components.ex
  lib/backpex/html/resource.ex
Labels: enhancement

#447 Update github actions via dependabot
  .github/dependabot.yml
Labels: ignore-for-release

#446 Update CI pipeline
  .github/workflows/ci.yml
Labels: ignore-for-release

#452 Fixed broken path to "What is a Field" page in Installation.md
  guides/get_started/installation.md
Labels: documentation

#458 Demo: remove newsletter stuff
  demo/config/runtime.exs
  demo/lib/demo/newsletter.ex
  demo/lib/demo/newsletter/brevo.ex
  demo/lib/demo/newsletter/contact.ex
  demo/lib/demo_web/live/home_live/index.ex
  demo/lib/demo_web/live/home_live/index.html.heex
Labels: demo

#459 Demo: improve Sentry data
  demo/lib/demo_web/endpoint.ex
  demo/lib/demo_web/router.ex
Labels: demo

#391 Delete `Backpex.Fields.ManyToMany` in favor of `Backpex.Fields.HasMany`
  demo/lib/demo_web/live/post_live.ex
  guides/fields/what-is-a-field.md
  guides/upgrading/v0.6.md
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/many_to_many.ex
  mix.exs
Labels: breaking-change

#464 Move item action changeset assignment to live resource
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
Labels: enhancement

#427 daisyUI theme support
  demo/assets/tailwind.config.js
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/live/home_live/index.ex
  demo/lib/demo_web/live/home_live/index.html.heex
  guides/get_started/installation.md
  guides/get_started/prerequisites.md
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/upload.ex
  lib/backpex/html/core_components.ex
  lib/backpex/html/form.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/form_component.html.heex
  lib/backpex/html/resource/resource_index_main.html.heex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/item_actions/show.ex
  lib/backpex/live_resource.ex
  lib/backpex/metric.ex
  lib/backpex/metrics/value.ex
Labels: enhancement

#390 Add "From" and "To" label to range filter inputs
  guides/custom_labels_and_translations/custom-labels-and-translations.md
  lib/backpex/filters/range.ex
Labels: enhancement

#466 Fix column toggle labels not clickable
  lib/backpex/html/resource.ex
Labels: bug

#467 Make toggle columns labels normal case again
  lib/backpex/html/resource/resource_index_table.html.heex
Labels: bug

#470 Fix toggle column width
  lib/backpex/html/resource.ex
Labels: bug

#476 Raise ecto no results error if id is not valid
  lib/backpex/resource.ex
Labels: enhancement

#471 Break words in upload field file list
  lib/backpex/fields/upload.ex
Labels: bug

#432 Balance hero text on landing page
  demo/lib/demo_web/live/home_live/index.html.heex
Labels: demo

#481 Fix `Backpex.Resource.update_all/6` when used without pubsub arg
  lib/backpex/resource.ex
Labels: bug

#465 Fix edit and new form crashes when all field fields are readonly
  lib/backpex/live_components/form_component.ex
Labels: bug

#303 Elixir 1.17 and OTP 27.0
  .github/workflows/ci.yml
  .tool-versions
  Dockerfile
  demo/mix.lock
  mix.exs
  mix.lock
Labels: dependencies, demo

#490 Update installation.md
  guides/get_started/installation.md
Labels: documentation

#491 Update mix.lock
  demo/mix.lock
Labels: ignore-for-release

#478 Add support for serial ids in HasMany field
  lib/backpex/fields/has_many.ex
Labels: bug
