Repository naymspace/backpex, pull requests merged in 2024-09, with the labels that each got.

#561 Add metric for published post count to demo
  demo/lib/demo_web/live/post_live.ex
Labels: demo

#567 Install postcss in demo application
  demo/package.json
  demo/yarn.lock
Labels: demo

#572 configure renovate and replace esbuild and tailwind packages
  .github/dependabot.yml
  .github/renovate.json
  compose.yml
  demo/config/config.exs
  demo/mix.exs
  demo/package.json
  demo/yarn.lock
  renovate.json
Labels: enhancement, demo

#587 Install esbuild and tailwind via config
  demo/config/config.exs
  demo/package.json
  demo/yarn.lock
Labels: demo

#586 Use a consistent formatting style
  lib/backpex/html/form.ex
  lib/backpex/html/html.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/metrics/value.ex
Labels: enhancement

#588 Remove unused dependencies
  demo/assets/js/app.js
  demo/config/config.exs
  demo/mix.exs
  demo/mix.lock
  demo/package.json
  demo/yarn.lock
Labels: demo

#555 Tests
  test/controllers/cookie_controller_test.exs
  test/plugs/theme_selector_plug_test.exs
Labels: enhancement

#594 Refactor caching steps in ci
  .github/workflows/ci.yml
Labels: ignore-for-release

#550 Remove landing page
  demo/lib/demo_web/controllers/redirect_controller.ex
  demo/lib/demo_web/live/home_live/index.ex
  demo/lib/demo_web/live/home_live/index.html.heex
  demo/lib/demo_web/router.ex
Labels: demo

#591 Remove show item action placement from docs
  guides/actions/item-actions.md
Labels: documentation

#566 Improve documentation and README
  README.md
  guides/get_started/installation.md
  guides/get_started/prerequisites.md
  mix.exs
Labels: documentation

#595 Update readme
  README.md
Labels: ignore-for-release

#592 Pass item to item action's `label` and `icon` function
  demo/lib/demo_web/item_actions/duplicate_tag.ex
  demo/lib/demo_web/item_actions/soft_delete.ex
  guides/actions/item-actions.md
  guides/upgrading/v0.7.md
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index.html.heex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/item_actions/delete.ex
  lib/backpex/item_actions/edit.ex
  lib/backpex/item_actions/item_action.ex
  lib/backpex/item_actions/show.ex
Labels: breaking-change

#613 add formatter config to hex package
  mix.exs
Labels: bug

#540 Support primary keys which are not called "id"
  demo/lib/demo/factory.ex
  demo/lib/demo/product.ex
  demo/lib/demo/short_link.ex
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/short_link_live.ex
  demo/lib/demo_web/router.ex
  demo/priv/repo/migrations/20240824063251_create_short_links.exs
  guides/get_started/installation.md
  lib/backpex/ecto/ecto_utils.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/live_resource.ex
  lib/backpex/resource.ex
  lib/backpex/router.ex
  test/ecto/ecto_utils_test.exs
Labels: feature

#610 Switch from Alpine to Ubuntu
  .docker/etc/bash.bashrc
  .docker/etc/bashrc.d/prompt.sh
  .docker/root/.bashrc
  .github/renovate.json
  Dockerfile
Labels: ignore-for-release
