Repository naymspace/backpex, pull requests merged in 2024-06, with the labels that each got.

#289 Fix typo, :genral -> :general
  lib/backpex.ex
Labels: enhancement

#297 handle 404 for resource items
  lib/backpex/live_resource.ex
  lib/backpex/resource.ex
Labels: bug

#269 Improve uploads and validation flow
  demo/lib/demo/product.ex
  demo/lib/demo/user.ex
  demo/lib/demo_web/item_actions/soft_delete.ex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/user_live.ex
  demo/lib/demo_web/resource_actions/upload.ex
  demo/priv/repo/migrations/20240529084100_add_images_to_products.exs
  demo/priv/repo/migrations/20240530093116_make_user_avatar_nullable.exs
  demo/priv/static/uploads/product/images/.gitignore
  guides/upgrading/v0.3.md
  lib/backpex/field.ex
  lib/backpex/fields/upload.ex
  lib/backpex/html/form.ex
  lib/backpex/item_actions/delete.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  lib/backpex/resource.ex
  mix.exs
Labels: breaking-change

#305 Install deps during release step in ci
  .github/workflows/ci.yml
Labels: ignore-for-release

#304 Update docs source_ref and source_url
  mix.exs
Labels: ignore-for-release

#340 Fix Learn More links in README
  README.md
Labels: documentation

#344 Fix images are not displayed in docs
  README.md
Labels: documentation

#342 Rename label of a field in the installation guide
  guides/get_started/installation.md
Labels: documentation

#346 Update what is backpex guide
  guides/about/what-is-backpex.md
Labels: documentation

#343 Improve config example in translations guide
  guides/translations/translations.md
Labels: documentation

#345 Turn sentry meta tag into component
  demo/lib/demo_web/components/core_components.ex
  demo/lib/demo_web/components/layouts/root.html.heex
Labels: demo

#341 Add documentation pull requests to release notes
  .github/release.yml
Labels: ignore-for-release

#338 Fix form error hint is only shown after second submit
  lib/backpex/live_components/form_component.ex
Labels: bug

#380 Update CI workflow to include pull requests for main and develop branches
  .github/workflows/ci.yml
Labels: ignore-for-release

#387 Fix `HasManyThrough` resets after selecting relation
  lib/backpex/resource.ex
Labels: bug

#379 Bump phoenix_html to 4.1.1
  demo/mix.exs
  demo/mix.lock
  lib/backpex/fields/has_many_through.ex
  mix.exs
  mix.lock
Labels: dependencies

#389 Remove empty state subtitle when no resources exist
  guides/translations/translations.md
  lib/backpex/html/resource.ex
Labels: enhancement

#400 Prevent PETAL from being split at linebreaks
  demo/lib/demo_web/live/home_live/index.html.heex
Labels: demo

#388 Add `create_button_label` option to live resource
  guides/custom_labels_and_translations/custom-labels-and-translations.md
  guides/live_resource/custom_button_labels.md
  lib/backpex/html/resource.ex
  lib/backpex/live_resource.ex
  mix.exs
Labels: feature

#411 Add `resource_created_message` option to live resource
  guides/custom_labels_and_translations/custom-labels-and-translations.md
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
Labels: feature

#418 Display newlines and whitespaces for textarea values
  lib/backpex/fields/textarea.ex
Labels: enhancement

#415 Remove floki
  demo/mix.lock
  lib/backpex/html/layout.ex
  mix.exs
  mix.lock
Labels: dependencies

#413 Improve documentation
  guides/get_started/installation.md
  guides/get_started/prerequisites.md
  lib/backpex/item_actions/item_action.ex
  lib/backpex/resource_action.ex
  mix.exs
Labels: documentation

#406 Pass persisted item to `consume_upload` function and pass `data` to item actions and resource actions
  demo/lib/demo_web/item_actions/duplicate_tag.ex
  demo/lib/demo_web/item_actions/soft_delete.ex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/user_live.ex
  demo/lib/demo_web/resource_actions/email.ex
  demo/lib/demo_web/resource_actions/upload.ex
  guides/actions/item-actions.md
  guides/actions/resource-actions.md
  guides/upgrading/v0.3.md
  guides/upgrading/v0.5.md
  lib/backpex/fields/upload.ex
  lib/backpex/item_actions/delete.ex
  lib/backpex/item_actions/edit.ex
  lib/backpex/item_actions/item_action.ex
  lib/backpex/item_actions/show.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/resource_action.ex
  mix.exs
Labels: breaking-change

#420 Remove non-existent email field from documentation
  guides/fields/what-is-a-field.md
Labels: documentation

#421 Use tailwind plugin for heroicons
  demo/assets/tailwind.config.js
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/item_actions/duplicate_tag.ex
  demo/lib/demo_web/item_actions/soft_delete.ex
  demo/lib/demo_web/live/film_review_live.ex
  demo/lib/demo_web/live/home_live/index.ex
  demo/lib/demo_web/live/home_live/index.html.heex
  demo/mix.exs
  demo/mix.lock
  guides/actions/item-actions.md
  guides/get_started/installation.md
  guides/upgrading/v0.5.md
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/upload.ex
  lib/backpex/html/core_components.ex
  lib/backpex/html/form.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/item_actions/delete.ex
  lib/backpex/item_actions/edit.ex
  lib/backpex/item_actions/show.ex
  lib/backpex/live_resource.ex
  mix.exs
  mix.lock
Labels: breaking-change

#423 Format `tailwind.config.js` in demo
  demo/assets/tailwind.config.js
Labels: demo

#437 Fix arrow icon is not displayed on landing page
  demo/lib/demo_web/live/home_live/index.html.heex
Labels: demo
