Repository naymspace/backpex, pull requests merged in 2024-08, with the labels that each got.

#513 Fixed warning run in erlang 27.0.1 & elixir 1.17.2-otp-27
  lib/backpex/html/resource.ex
  lib/backpex/router.ex
Labels: bug

#525 Small adjustments
  demo/config/prod.exs
  demo/lib/demo_web/live/home_live/index.ex
  demo/mix.lock
Labels: ignore-for-release

#526 Remove depth to fix dependabot errors
  demo/mix.exs
  demo/mix.lock
Labels: ignore-for-release

#527 Bump heroicons to 2.1.5 in /demo
  demo/mix.exs
  demo/mix.lock
Labels: dependencies

#468 daisyUI theme selector
  demo/assets/js/app.js
  demo/assets/tailwind.config.js
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/components/layouts/root.html.heex
  demo/lib/demo_web/router.ex
  guides/get_started/installation.md
  lib/backpex/controllers/cookie_controller.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/plugs/theme_selector.ex
  lib/backpex/router.ex
Labels: demo

#529 Fix HasMany and MultiSelect search field not working
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/multi_select.ex
Labels: bug

#535 Fix links
  lib/backpex/live_resource.ex
Labels: documentation

#539 Fix misplaced bracket in installation instructions
  guides/get_started/installation.md
Labels: documentation

#548 Move backpex tests into backpex project
  test/ecto/amount_type_test.exs
Labels: ignore-for-release

#549 remove demo SSL opts
  demo/config/prod.exs
Labels: bug, demo

#537 Check for named binding before joining
  lib/backpex/resource.ex
Labels: bug

#556 Fixed index_editable in Backpex.Fields.Number
  lib/backpex/fields/number.ex
Labels: bug
