Repository naymspace/backpex, pull requests merged in 2024-11, with the labels that each got.

#653 Update plausible installation
  mix.exs
Labels: ignore-for-release

#651 improvement: don't pin AshPostgres to an old version
  mix.exs
  mix.lock
Labels: dependencies

#650 Improve ash setup
  demo/.formatter.exs
  demo/config/config.exs
  demo/config/runtime.exs
  demo/lib/demo/application.ex
  demo/lib/demo/helpdesk/ticket.ex
  demo/lib/demo/repo.ex
  demo/priv/repo/migrations/20241022065649_install_ash-functions_extension_3.exs.exs
  demo/priv/repo/migrations/20241022065651_create_ticket.exs.exs
  demo/priv/repo_ash/migrations/.formatter.exs
  demo/priv/resource_snapshots/repo/extensions.json
  demo/priv/resource_snapshots/repo/tickets/20241103111608.json
Labels: demo

#655 improve credo config
  .credo.exs
  demo/lib/demo/short_link.ex
  demo/lib/demo_web/item_actions/soft_delete.ex
  lib/backpex/adapters/ecto.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/live_resource.ex
  test/doc_test.exs
Labels: ignore-for-release

#657 Improve generated release notes
  .github/release.yml
  .github/renovate.json
Labels: ignore-for-release

#658 Refactor `field_input` component
  guides/fields/custom-fields.md
  guides/fields/readonly.md
  guides/upgrading/v0.9.md
  lib/backpex/field.ex
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/textarea.ex
  lib/backpex/fields/upload.ex
  lib/backpex/fields/url.ex
  lib/backpex/html/form.ex
  mix.exs
Labels: breaking-change

#660 Fix incorrect configuration in installation guide
  guides/get_started/installation.md
Labels: documentation

#664 Fix error when submitting short link with existing url suffix
  demo/lib/demo/short_link.ex
  demo/priv/repo/migrations/20241112092150_drop_short_links_unique_index.exs
Labels: bug

#665 Add ‘rows' attribute to the textarea, with a default value of 2 rows.
  demo/lib/demo_web/live/post_live.ex
  lib/backpex/fields/textarea.ex
Labels: enhancement

#659 Refactor Long Quote Block in LiveResource
  guides/upgrading/v0.9.md
  lib/backpex/adapters/ecto.ex
  lib/backpex/field.ex
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
Labels: enhancement

#645 Automerge github actions dependency updates
  .github/renovate.json
Labels: ignore-for-release

#672 Rename item and resource action `init_change/1` callback to `base_schema/1`
  demo/lib/demo_web/item_actions/duplicate_tag.ex
  guides/upgrading/v0.9.md
  lib/backpex/item_actions/item_action.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  lib/backpex/resource_action.ex
Labels: breaking-change

#675 Change expected return values of item and resource action `handle` functions
  demo/lib/demo_web/item_actions/duplicate_tag.ex
  demo/lib/demo_web/item_actions/soft_delete.ex
  demo/lib/demo_web/resource_actions/email.ex
  demo/lib/demo_web/resource_actions/upload.ex
  guides/upgrading/v0.9.md
  lib/backpex/item_actions/delete.ex
  lib/backpex/item_actions/edit.ex
  lib/backpex/item_actions/item_action.ex
  lib/backpex/item_actions/show.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  lib/backpex/resource_action.ex
Labels: breaking-change

#678 Fix reference warning in docs
  lib/backpex/resource_action.ex
Labels: ignore-for-release

#681 Fix custom `handle_event` and `handle_info` couldn't be defined in Live Resource
  lib/backpex/live_resource.ex
Labels: enhancement
