Repository naymspace/backpex, pull requests merged in 2024-10, with the labels that each got.

#620 Set `pinDigests` to false for ubuntu
  .github/renovate.json
Labels: ignore-for-release

#628 Allow function for `init_order` configuration
  demo/lib/demo_web/live/user_live.ex
  guides/live_resource/ordering.md
  lib/backpex/live_resource.ex
Labels: feature

#632 Allow passing a function to format a date or datetime
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
Labels: feature

#641 Add plausible to docs
  mix.exs
Labels: ignore-for-release

#608 Introduction of the adapter pattern for flexible datasources
  .credo.exs
  .formatter.exs
  demo/.formatter.exs
  demo/config/config.exs
  demo/config/runtime.exs
  demo/lib/demo/application.ex
  demo/lib/demo/factory.ex
  demo/lib/demo/helpdesk/ticket.ex
  demo/lib/demo/repo.ex
  demo/lib/demo/support.ex
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/item_actions/soft_delete.ex
  demo/lib/demo_web/live/address_live.ex
  demo/lib/demo_web/live/category_live.ex
  demo/lib/demo_web/live/film_review_live.ex
  demo/lib/demo_web/live/invoice_live.ex
  demo/lib/demo_web/live/post_live.ex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/short_link_live.ex
  demo/lib/demo_web/live/tag_live.ex
  demo/lib/demo_web/live/ticket_live.ex
  demo/lib/demo_web/live/user_live.ex
  demo/lib/demo_web/router.ex
  demo/mix.exs
  demo/mix.lock
  demo/priv/repo/seeds.exs
  demo/priv/repo_ash/migrations/.formatter.exs
  demo/priv/repo_ash/migrations/20241022065649_install_ash-functions_extension_3.exs
  demo/priv/repo_ash/migrations/20241022065651_create_ticket.exs
  demo/priv/resource_snapshots/repo_ash/extensions.json
  demo/priv/resource_snapshots/repo_ash/tickets/20241022065651.json
  guides/get_started/installation.md
  guides/live_resource/item-query.md
  guides/live_resource/listen-to-pubsub-events.md
  guides/live_resource/ordering.md
  guides/upgrading/v0.7.md
  guides/upgrading/v0.8.md
  lib/backpex/adapter.ex
  lib/backpex/adapters/ash.ex
  lib/backpex/adapters/ecto.ex
  lib/backpex/ecto/ecto_utils.ex
  lib/backpex/field.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/item_actions/delete.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  lib/backpex/metric.ex
  lib/backpex/resource.ex
  lib/backpex/router.ex
  mix.exs
  mix.lock
  test/ecto/ecto_utils_test.exs
Labels: breaking-change

#648 Fix incorrect live resource configuration in docs
  guides/get_started/installation.md
  guides/upgrading/v0.8.md
Labels: documentation
