Repository naymspace/backpex, pull requests merged in 2024-12, with the labels that each got.

#684 Add link to github releases to package
  mix.exs
Labels: ignore-for-release

#685 Add website url to package
  mix.exs
Labels: ignore-for-release

#652 Add `Backpex.Fields.Time`
  lib/backpex/fields/time.ex
Labels: feature

#635 Add save & continue editing button
  guides/custom_labels_and_translations/custom-labels-and-translations.md
  guides/upgrading/v0.9.md
  lib/backpex/html/resource/form_component.html.heex
  lib/backpex/live_components/form_component.ex
Labels: feature

#695 Add `Backpex.ItemAction.default_actions/0`
  lib/backpex/item_actions/item_action.ex
  lib/backpex/live_resource.ex
Labels: enhancement

#700 Add missing `max_entries` key to upload field options in resource action
  demo/lib/demo_web/resource_actions/upload.ex
Labels: demo

#702 Improve custom fields docs
  guides/fields/custom-fields.md
Labels: documentation

#706 Set renovate `rangeStrategy` to `update-lockfile` for mix deps
  .github/renovate.json
Labels: ignore-for-release

#724 Include hint about default admin route configuration
  guides/get_started/installation.md
Labels: documentation
