Repository naymspace/backpex, pull requests merged in 2025-02, with the labels that each got.

#822 add upload progress indicator
  lib/backpex/fields/upload.ex
Labels: feature

#827 Remove `Ecto.Query` import in live resources
  demo/lib/demo_web/live/post_live.ex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/user_live.ex
  demo/mix.lock
  guides/upgrading/v0.11.md
  lib/backpex/live_resource.ex
  mix.exs
  mix.lock
Labels: breaking-change

#832 Configure additionalBranchPrefix renovate option
  .github/renovate.json
Labels: ignore-for-release

#817 Always build image in ci pipeline
  .github/workflows/ci.yml
Labels: ignore-for-release

#836 Set additionalBranchPrefix to `baseDir`
  .github/renovate.json
Labels: ignore-for-release

#846 Test category live
  demo/mix.lock
  demo/test/demo_web/live/category_live_test.exs
  demo/test/demo_web/live/tag_live_test.exs
  demo/test/support/live_resource_tests.ex
Labels: demo

#849 add after_main position to render_resource_slot and improve docs
  lib/backpex/html/resource/resource_form.html.heex
  lib/backpex/html/resource/resource_index.html.heex
  lib/backpex/html/resource/resource_show.html.heex
  lib/backpex/live_resource.ex
Labels: feature

#856 Fix params not passed to `get_path` in default `return_to` route
  lib/backpex/live_resource.ex
  lib/backpex/router.ex
Labels: bug

#862 improve syntax highlighting in documentation
  guides/get_started/installation.md
  mix.exs
  mix.lock
Labels: documentation

#871 Bump backpex version in installation guide to latest version
  guides/get_started/installation.md
Labels: documentation

#869 Assign missing rows in readonly textarea field
  lib/backpex/fields/textarea.ex
Labels: bug

#894 Fix MultiSelect crash when returning non strings as options
  lib/backpex/fields/multi_select.ex
Labels: bug

#895 Add reusable edit card component
  guides/upgrading/v0.11.md
  lib/backpex/html/core_components.ex
  lib/backpex/html/form.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/form_component.html.heex
  mix.lock
Labels: feature

#874 Add `index_editable` support for `Backpex.Fields.Boolean`
  demo/lib/demo_web/live/post_live.ex
  lib/backpex/fields/boolean.ex
Labels: feature

#904 Fix empty panels are displayed
  lib/backpex/html/resource/form_component.html.heex
Labels: ignore-for-release
