Repository naymspace/backpex, pull requests merged in 2025-08, with the labels that each got.

#1351 Remove `render_form_readonly` callback from fields
  guides/fields/readonly.md
  guides/upgrading/v0.14.md
  lib/backpex/field.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/textarea.ex
  lib/backpex/fields/time.ex
  lib/backpex/html/resource.ex
Labels: breaking-change

#957 Add `backpex.install` command
  demo/mix.exs
  demo/mix.lock
  guides/get_started/installation.md
  lib/mix/helpers.ex
  lib/mix/tasks/backpex.install.ex
  mix.exs
  mix.lock
  priv/templates/layouts/admin.html.heex
Labels: feature

#1400 Fix 0.13.0 Upgrade Guide
  guides/upgrading/v0.13.md
Labels: documentation

#1385 Remove hardcoded width from index edit inputs
  guides/upgrading/v0.14.md
  guides/upgrading/v0.15.md
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/time.ex
  mix.exs
Labels: breaking-change

#1409 Update `Listen to PubSub Events` guide
  guides/live_resource/listen-to-pubsub-events.md
Labels: documentation

#1361 Fix entries were excluded from index view under certain conditions
  lib/backpex/adapters/ecto.ex
  test/adapters/ecto_test.exs
Labels: bug
