Repository naymspace/backpex, pull requests merged in 2025-05, with the labels that each got.

#1121 Enable lock file maintenance
  .github/renovate.json
Labels: ignore-for-release

#1134 update readme and screenshot
  README.md
  demo/lib/demo_web/components/layouts/root.html.heex
  mix.exs
  priv/static/images/screenshot.png
Labels: documentation

#1046 split LiveResource
  .credo.exs
  demo/lib/demo_web/live/tag_live.ex
  guides/live_resource/on_mount-hook.md
  guides/upgrading/v0.13.md
  lib/backpex/item_actions/edit.ex
  lib/backpex/item_actions/show.ex
  lib/backpex/live_resource.ex
  lib/backpex/live_resource/form.ex
  lib/backpex/live_resource/index.ex
  lib/backpex/live_resource/show.ex
  lib/backpex/router.ex
  mix.exs
Labels: enhancement

#1153 disable docs for ok and noreply
  lib/backpex_web.ex
Labels: documentation

#1185 Fix `HasMany` shows error if input was not used yet
  lib/backpex/fields/has_many.ex
Labels: bug
