Repository naymspace/backpex, pull requests merged in 2025-09, with the labels that each got.

#1463 Update test matrix
  .github/workflows/ci.yml
Labels: ignore-for-release

#1465 Fix live updates not working sometimes
  lib/backpex/live_resource/index.ex
Labels: bug

#1471 fixing install documentation
  guides/get_started/installation.md
Labels: documentation

#1516 Configure merge group
  .github/workflows/ci.yml
Labels: ignore-for-release

#1529 Fix some errors in the documentation
  guides/live_resource/on_mount-hook.md
  lib/backpex/item_actions/delete.ex
  lib/backpex/item_actions/edit.ex
Labels: documentation

#1472 Add `Backpex.Fields.Email`
  guides/fields/index-edit.md
  guides/fields/what-is-a-field.md
  lib/backpex/fields/email.ex
Labels: feature

#1530 Remove rebase instructions from renovate.json
  .github/renovate.json
Labels: ignore-for-release

#1466 Simplify query function in MultiSelect filter
  lib/backpex/filters/multi_select.ex
Labels: enhancement

#1532 Fix spelling mistakes in guides
  guides/about/what-is-backpex.md
  guides/authorization/live-resource-authorization.md
  guides/fields/custom-alias.md
Labels: documentation

#1554 Enhance `order_link/1` component
  lib/backpex/html/resource.ex
Labels: enhancement

#1563 Update renovate.json
  .github/renovate.json
Labels: ignore-for-release

#1531 Auto-detect app.js or app.ts in `backpex.install` task
  lib/mix/tasks/backpex.install.ex
Labels: enhancement

#1571 Set `minimumReleaseAge` to 14 days
  .github/renovate.json
Labels: ignore-for-release

#1544 Fix picker appearance for select input
  lib/backpex/html/form.ex
Labels: bug

#1572 Revert "Fix picker appearance for select input"
  lib/backpex/html/form.ex
Labels: ignore-for-release

#1573 Set `internalChecksFilter` to strict
  .github/renovate.json
Labels: ignore-for-release

#1576 Improve `input_label/1` component
  guides/fields/custom-fields.md
  guides/fields/readonly.md
  guides/upgrading/v0.16.md
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/email.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/multi_select.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/textarea.ex
  lib/backpex/fields/time.ex
  lib/backpex/fields/upload.ex
  lib/backpex/fields/url.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
Labels: enhancement
