Repository naymspace/backpex, pull requests merged in 2025-06, with the labels that each got.

#1218 Pass assigns to query and options filter callbacks
  demo/lib/demo_web/filters/post_category_select.ex
  demo/lib/demo_web/filters/post_published.ex
  demo/lib/demo_web/filters/post_user_multi_select.ex
  guides/upgrading/v0.14.md
  lib/backpex/adapters/ecto.ex
  lib/backpex/filters/boolean.ex
  lib/backpex/filters/filter.ex
  lib/backpex/filters/multi_select.ex
  lib/backpex/filters/range.ex
  lib/backpex/filters/select.ex
  lib/backpex/html/resource.ex
  mix.exs
Labels: breaking-change

#1233 Update `input/1` component
  guides/upgrading/v0.14.md
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/select.ex
  lib/backpex/html/form.ex
Labels: breaking-change

#1249 add config_schema helper for fields
  lib/backpex/field.ex
Labels: feature

#1098 Improve installation guide
  guides/get_started/installation.md
  guides/translations/translations.md
Labels: documentation

#1124 Test a11y with playwright
  .github/workflows/ci.yml
  Dockerfile
  demo/.env.test
  demo/config/test.exs
  demo/lib/demo/ecto_factory.ex
  demo/mix.exs
  demo/mix.lock
  demo/package.json
  demo/test/demo_web/browser/address_browser_test.exs
  demo/test/demo_web/browser/category_browser_test.exs
  demo/test/demo_web/browser/film_review_browser_test.exs
  demo/test/demo_web/browser/invoice_browser_test.exs
  demo/test/demo_web/browser/post_browser_test.exs
  demo/test/demo_web/browser/product_browser_test.exs
  demo/test/demo_web/browser/short_link_browser_test.exs
  demo/test/demo_web/browser/tag_browser_test.exs
  demo/test/demo_web/browser/ticket_browser_test.exs
  demo/test/demo_web/browser/user_browser_test.exs
  demo/test/support/a11y_assertions.ex
  demo/test/test_helper.exs
  demo/yarn.lock
Labels: enhancement, demo
