Repository naymspace/backpex, pull requests merged in 2025-04, with the labels that each got.

#1039 Update code to use the new Tailwind CSS `not-*` variant
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/time.ex
Labels: enhancement

#951 improve modal component
  demo/mix.lock
  guides/upgrading/v0.13.md
  lib/backpex/fields/has_many_through.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource/form_component.html.heex
  lib/backpex/html/resource/resource_index.html.heex
  lib/backpex/live_resource.ex
  mix.lock
Labels: feature

#1037 Fix soft deleting users in the demo
  demo/lib/demo_web/item_actions/user_soft_delete.ex
  demo/lib/demo_web/live/post_live.ex
  demo/lib/demo_web/live/user_live.ex
Labels: bug, demo

#1043 fix and improve flash message styles and add alert component
  demo/lib/demo_web/live/film_review_live.ex
  demo/lib/demo_web/live/ticket_live.ex
  lib/backpex/html/layout.ex
Labels: feature

#1045 reduce LiveResource assigns
  demo/lib/demo_web/item_actions/user_soft_delete.ex
  guides/upgrading/v0.13.md
  lib/backpex/adapters/ecto.ex
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/html/resource.ex
  lib/backpex/item_actions/delete.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
Labels: enhancement

#1091 Add `help_text` field option
  demo/lib/demo_web/live/user_live.ex
  demo/mix.lock
  guides/upgrading/v0.13.md
  lib/backpex/field.ex
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/boolean.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/multi_select.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/textarea.ex
  lib/backpex/fields/time.ex
  lib/backpex/fields/upload.ex
  lib/backpex/fields/url.ex
  lib/backpex/html/form.ex
  mix.exs
  mix.lock
Labels: feature

#1063 implement error toasts
  guides/upgrading/v0.13.md
  lib/backpex/html/layout.ex
  priv/gettext/backpex.pot
Labels: feature
