Repository naymspace/backpex, pull requests merged in 2025-03, with the labels that each got.

#818 Replace Alpine.js with JS hooks
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  assets/js/backpex.js
  assets/js/hooks/_cancel_entry.js
  assets/js/hooks/_drag_hover.js
  assets/js/hooks/_sidebar_sections.js
  assets/js/hooks/_sticky_actions.js
  assets/js/hooks/_theme_selector.js
  assets/js/hooks/_tooltip.js
  assets/js/hooks/index.js
  demo/assets/js/app.js
  demo/assets/tailwind.config.js
  demo/config/config.exs
  demo/lib/demo_web/live/category_live.ex
  demo/mix.lock
  demo/package.json
  demo/yarn.lock
  guides/get_started/installation.md
  guides/upgrading/v0.11.md
  lib/backpex/fields/upload.ex
  lib/backpex/filters/multi_select.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index_main.html.heex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  lib/backpex_web.ex
  mix.exs
  package.json
  yarn.lock
Labels: feature, breaking-change

#887 make pubsub config optional
  demo/config/config.exs
  demo/lib/demo_web/live/address_live.ex
  demo/lib/demo_web/live/category_live.ex
  demo/lib/demo_web/live/film_review_live.ex
  demo/lib/demo_web/live/invoice_live.ex
  demo/lib/demo_web/live/post_live.ex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/short_link_live.ex
  demo/lib/demo_web/live/tag_live.ex
  demo/lib/demo_web/live/ticket_live.ex
  demo/lib/demo_web/live/user_live.ex
  guides/get_started/installation.md
  guides/live_resource/listen-to-pubsub-events.md
  guides/upgrading/v0.11.md
  guides/upgrading/v0.12.md
  lib/backpex/live_resource.ex
  lib/backpex/resource.ex
Labels: feature

#948 Improve installation guide
  guides/get_started/installation.md
Labels: documentation

#952 add class attribute to app_shell component
  lib/backpex/html/layout.ex
Labels: feature

#847 Test tickets live
  demo/lib/demo/ash_factory.ex
  demo/lib/demo/ecto_factory.ex
  demo/mix.exs
  demo/mix.lock
  demo/priv/repo/seeds.exs
  demo/test/demo_web/live/category_live_test.exs
  demo/test/demo_web/live/tag_live_test.exs
  demo/test/demo_web/live/ticket_live_test.exs
Labels: demo

#964 Add option to disable "Save & Continue editing" button
  guides/upgrading/v0.12.md
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
Labels: feature

#974 Fix order of params passed to `return_to_path/6`
  lib/backpex/live_components/form_component.ex
Labels: ignore-for-release

#981 Improve "Create layout" section in installation guide
  guides/get_started/installation.md
Labels: documentation

#965 Fix "Save & Continue editing" button when primary key is not named `id`
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
Labels: bug

#999 Add error handling for missing routes in Router functions
  lib/backpex/router.ex
Labels: enhancement

#1002 Add `translate/1` callback to live resource
  demo/lib/demo_web/item_actions/soft_delete.ex
  demo/lib/demo_web/live/user_live.ex
  demo/mix.lock
  guides/custom_labels_and_translations/custom-labels-and-translations.md
  guides/searching/basic-search.md
  guides/translations/translations.md
  guides/upgrading/v0.12.md
  lib/backpex.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/multi_select.ex
  lib/backpex/fields/upload.ex
  lib/backpex/filters/multi_select.ex
  lib/backpex/filters/range.ex
  lib/backpex/gettext.ex
  lib/backpex/html/core_components.ex
  lib/backpex/html/form.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/form_component.html.heex
  lib/backpex/html/resource/resource_index.html.heex
  lib/backpex/html/resource/resource_index_main.html.heex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/item_actions/delete.ex
  lib/backpex/item_actions/edit.ex
  lib/backpex/item_actions/item_action.ex
  lib/backpex/item_actions/show.ex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  mix.exs
  priv/gettext/backpex.pot
Labels: breaking-change

#920 Upgrade to Tailwind 4 and daisyUI 5
  Dockerfile
  assets/js/hooks/_tooltip.js
  demo/.stylelintrc.json
  demo/assets/css/app.css
  demo/assets/css/tailwind_heroicons.js
  demo/assets/tailwind.config.js
  demo/config/config.exs
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/live/post_live.ex
  demo/mix.exs
  demo/mix.lock
  demo/package.json
  demo/priv/repo/seeds.exs
  guides/get_started/installation.md
  guides/upgrading/v0.12.md
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/time.ex
  lib/backpex/fields/upload.ex
  lib/backpex/filters/multi_select.ex
  lib/backpex/filters/range.ex
  lib/backpex/filters/select.ex
  lib/backpex/html/core_components.ex
  lib/backpex/html/form.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/form_component.html.heex
  lib/backpex/html/resource/resource_form_main.html.heex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/metric.ex
  mix.lock
Labels: breaking-change

#1029 Fix checkbox validation not updating when clicking on checkbox label
  lib/backpex/html/form.ex
Labels: bug
