Repository naymspace/backpex, pull requests merged in 2025-07, with the labels that each got.

#1155 add default values in ecto adapter config
  demo/lib/demo/invoice.ex
  demo/lib/demo_web/live/invoice_live.ex
  lib/backpex/adapters/ash.ex
  lib/backpex/adapters/ecto.ex
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/live_resource.ex
  lib/backpex/live_resource/form.ex
  lib/backpex/live_resource/index.ex
Labels: feature

#1295 Fix resource action routes not added in some cases
  lib/backpex/router.ex
  test/plugs/theme_selector_plug_test.exs
  test/router_test.exs
Labels: ignore-for-release

#1308 Require `changeset/3` in ItemActions
  guides/actions/item-actions.md
  guides/upgrading/v0.14.md
  lib/backpex/item_actions/item_action.ex
  mix.exs
Labels: breaking-change

#1326 Fix `@source` definitions in installation guide
  guides/get_started/installation.md
Labels: documentation

#1330 Add documentation for `except` keyword for item action placement
  guides/actions/item-actions.md
Labels: documentation

#1310 Update renovate configuration
  .github/renovate.json
Labels: ignore-for-release

#1352 Show plural name as page title for resource actions
  lib/backpex/live_resource/index.ex
Labels: enhancement

#1353 Fix index edit not shown behind resource action modal
  lib/backpex/field.ex
Labels: bug
