Repository naymspace/backpex, pull requests merged in 2025-01, with the labels that each got.

#739 Update version strings in `mix.exs`
  mix.exs
Labels: enhancement

#743 Improve renovate config
  .github/renovate.json
Labels: ignore-for-release

#753 Add missing automerge
  .github/renovate.json
Labels: ignore-for-release

#755 Update dependency ash to v3.4.54
  demo/mix.lock
  mix.lock
Labels: dependencies, elixir

#756 Update dependency ash_postgres to v2.4.21
  demo/mix.lock
  mix.lock
Labels: dependencies, elixir

#687 Update dependency phoenix_live_view to v1.0
  demo/assets/css/app.css
  demo/assets/tailwind.config.js
  demo/lib/demo_web/components/layouts/admin.html.heex
  demo/lib/demo_web/components/layouts/app.html.heex
  demo/lib/demo_web/components/layouts/root.html.heex
  demo/lib/demo_web/live/post_live.ex
  demo/lib/demo_web/live/product_live.ex
  demo/lib/demo_web/live/user_live.ex
  demo/mix.exs
  demo/mix.lock
  lib/backpex/fields/belongs_to.ex
  lib/backpex/fields/currency.ex
  lib/backpex/fields/date.ex
  lib/backpex/fields/date_time.ex
  lib/backpex/fields/has_many.ex
  lib/backpex/fields/has_many_through.ex
  lib/backpex/fields/inline_crud.ex
  lib/backpex/fields/multi_select.ex
  lib/backpex/fields/number.ex
  lib/backpex/fields/select.ex
  lib/backpex/fields/text.ex
  lib/backpex/fields/time.ex
  lib/backpex/fields/upload.ex
  lib/backpex/fields/url.ex
  lib/backpex/filters/boolean.ex
  lib/backpex/filters/multi_select.ex
  lib/backpex/filters/range.ex
  lib/backpex/filters/select.ex
  lib/backpex/html/core_components.ex
  lib/backpex/html/form.ex
  lib/backpex/html/layout.ex
  lib/backpex/html/resource.ex
  lib/backpex/html/resource/form_component.html.heex
  lib/backpex/html/resource/resource_form.html.heex
  lib/backpex/html/resource/resource_index.html.heex
  lib/backpex/html/resource/resource_index_table.html.heex
  lib/backpex/html/resource/resource_show.html.heex
  lib/backpex/live_components/form_component.ex
  lib/backpex/live_resource.ex
  lib/backpex/metrics/value.ex
  mix.exs
  mix.lock
Labels: dependencies, elixir

#758 Improve code quality
  lib/backpex/fields/upload.ex
  lib/backpex/live_components/form_component.ex
Labels: ignore-for-release

#761 Fix empty upload not showing error on save
  lib/backpex/fields/upload.ex
  lib/backpex/live_components/form_component.ex
Labels: bug

#767 Add demo label to Dockerfile updates
  .github/renovate.json
Labels: ignore-for-release

#538 Add integration tests for demo application
  .github/renovate.json
  demo/config/test.exs
  demo/mix.exs
  demo/mix.lock
  demo/test/demo_web/tag_live_test.exs
  demo/test/support/conn_case.ex
  demo/test/support/data_case.ex
  demo/test/support/live_resource_tests.ex
  lib/backpex/html/resource.ex
Labels: demo

#780 Downgrade `phoenix_test` to 0.5.0
  demo/mix.exs
  demo/mix.lock
Labels: ignore-for-release

#784 replace libcluster with dns_cluster
  demo/config/dev.exs
  demo/config/runtime.exs
  demo/config/test.exs
  demo/lib/demo/application.ex
  demo/mix.exs
  demo/mix.lock
Labels: demo

#782 fix demo logout link
  demo/lib/demo_web/components/layouts/admin.html.heex
Labels: demo

#795 Fix warning in Dockerfile
  Dockerfile
Labels: ignore-for-release

#796 Use ubuntu-noble-20241015
  Dockerfile
Labels: dependencies, docker, demo

#785 item_query refactoring
  lib/backpex/adapters/ecto.ex
  lib/backpex/live_resource.ex
Labels: enhancement

#799 Build docs with warnings as errors in ci
  .github/workflows/ci.yml
Labels: ignore-for-release

#809 Update renovate config
  .github/release.yml
  .github/renovate.json
Labels: ignore-for-release

#813 Disable renovate automerge feature for docker datasource
  .github/renovate.json
Labels: ignore-for-release

#794 Add external upload support for the Upload field.
  lib/backpex/fields/upload.ex
Labels: feature
